### ISSUE TITLE
Checklist de tarefas a serem executadas.

### ISSUE THREAD

**Issue by luis0ares** [iguit0/xi-sacsis-admin#1]
Operações de e cadastro login do sistema
- [x] Cadastro de usuários
- [x] Login
- [x] Modificar senha após o login com a senha temporária

Operações após usuário logado: **Participante** e **Administrador**
- [x] Editar dados de perfil.
- [x] Visualizar a programação do evento.
- [x]  - Modal de visualização de mais informações do evento da programação
- [x] Controle de inscrição nos minicursos oferecidos.

Operações após usuário logado: **Participante**
- [x] Exibir texto sobre pagamento

Operações após usuário logado: **Administrador**
- [x] Visualizar, modificar e remover participantes (usuários) cadastrados.
- [x] Visualizar e remover ministrantes cadastrados.
- [x] Visualizar, modificar e remover minicursos e palestras cadastrados pelos ministrantes.
- [x] Gerar link de cadastro de ministrantes.
- [x] Visualizar e editar lotes.
- [x] Validar (e invalidar) pagamentos de inscrição.
- [x] CRUD das atividades na programação (**palestras**, **minicursos** e **outros eventos**).
- [x] Baixar planilha da relação de participantes e pagamentos.
- [x] Baixar planilha da relação de ministrantes
- [x] Baixar planilha da programação cadastrada.

Outras operações.
- [x] Login automático com a validação do token.
- [x] Sair do sistema.
- [x] Formulário de cadastro de ministrantes incluindo minicurso e palestra (depende do tipo do formulário)
